/**
 * Vehicle Technical Datasheet
 *
 * Curated database of technical specifications for the premium/supercar brands
 * commonly found at Attra. Data is matched by brand + model keywords.
 *
 * Serves two purposes:
 *  1. Enriches vehicle pages with authoritative technical data (engine, weight,
 *     dimensions, acceleration, etc.) that AutoConf doesn't provide.
 *  2. Increases page word count and semantic depth for SEO.
 *
 * When AutoConf already provides a field (e.g. horsepower), the live value
 * takes precedence — the datasheet fills gaps only.
 */

export interface VehicleDatasheet {
	brand: string
	model: string
	matchKeywords: string[]
	engine: string
	displacement: string
	power: string
	torque: string
	acceleration: string
	topSpeed: string
	transmission: string
	drivetrain: string
	weight: string
	fuelConsumption?: string
	trunkCapacity?: string
	length?: string
	width?: string
	height?: string
	wheelbase?: string
	tires?: string
	brakes?: string
	fuelTankCapacity?: string
	seatingCapacity?: string
	warranty?: string
	highlights: string[]
}

const DATASHEETS: VehicleDatasheet[] = [
	{
		brand: 'Porsche',
		model: '911 Carrera',
		matchKeywords: ['911', 'carrera'],
		engine: 'Boxer 6 cilindros biturbo',
		displacement: '2.981 cc',
		power: '385 cv a 6.500 rpm',
		torque: '450 Nm entre 1.950–5.000 rpm',
		acceleration: '4,2 s (0–100 km/h)',
		topSpeed: '293 km/h',
		transmission: 'PDK 8 marchas',
		drivetrain: 'Tração traseira (RWD)',
		weight: '1.505 kg',
		fuelConsumption: '8,9 L/100 km (combinado)',
		trunkCapacity: '132 L (dianteiro)',
		length: '4.519 mm',
		width: '1.852 mm',
		height: '1.300 mm',
		wheelbase: '2.450 mm',
		tires: 'Dianteiro: 245/35 ZR20 | Traseiro: 305/30 ZR21',
		brakes: 'Discos ventilados perfurados, 350 mm (d) / 350 mm (t)',
		fuelTankCapacity: '64 L',
		seatingCapacity: '2+2 lugares',
		warranty: 'Garantia de fábrica Porsche',
		highlights: [
			'Motor boxer refrigerado a água com injeção direta',
			'Sistema PASM (Porsche Active Suspension Management)',
			'Modo Sport e Sport Plus com mapeamento dinâmico',
			'Porsche Communication Management (PCM) com tela de 10,9"',
			'Freios de alto desempenho com pinças de 4 pistões',
		],
	},
	{
		brand: 'Porsche',
		model: '911 Turbo S',
		matchKeywords: ['911', 'turbo'],
		engine: 'Boxer 6 cilindros biturbo',
		displacement: '3.745 cc',
		power: '650 cv a 6.750 rpm',
		torque: '800 Nm entre 2.500–4.000 rpm',
		acceleration: '2,7 s (0–100 km/h)',
		topSpeed: '330 km/h',
		transmission: 'PDK 8 marchas',
		drivetrain: 'Tração integral (AWD)',
		weight: '1.640 kg',
		fuelConsumption: '12,3 L/100 km (combinado)',
		length: '4.535 mm',
		width: '1.900 mm',
		height: '1.303 mm',
		wheelbase: '2.450 mm',
		tires: 'Dianteiro: 255/35 ZR20 | Traseiro: 315/30 ZR21',
		brakes: 'PCCB carbono-cerâmicos, 420 mm (d) / 390 mm (t)',
		fuelTankCapacity: '67 L',
		seatingCapacity: '2+2 lugares',
		warranty: 'Garantia de fábrica Porsche',
		highlights: [
			'Turbo de geometria variável exclusivo',
			'Launch Control integrado ao PDK',
			'Suspensão adaptativa PASM Sport',
			'Rear-axle steering para agilidade em baixa e estabilidade em alta',
			'Freios carbono-cerâmicos PCCB de série',
		],
	},
	{
		brand: 'Porsche',
		model: 'Cayenne',
		matchKeywords: ['cayenne'],
		engine: 'V6 turbo',
		displacement: '2.995 cc',
		power: '353 cv a 5.400–6.400 rpm',
		torque: '500 Nm entre 1.340–5.300 rpm',
		acceleration: '5,9 s (0–100 km/h)',
		topSpeed: '248 km/h',
		transmission: 'Tiptronic S 8 marchas',
		drivetrain: 'Tração integral (AWD)',
		weight: '2.030 kg',
		fuelConsumption: '11,4 L/100 km (combinado)',
		trunkCapacity: '772 L',
		length: '4.930 mm',
		width: '1.983 mm',
		height: '1.673 mm',
		wheelbase: '2.895 mm',
		fuelTankCapacity: '75 L',
		seatingCapacity: '5 lugares',
		warranty: 'Garantia de fábrica Porsche',
		highlights: [
			'Chassi com molas de aço adaptativas',
			'Porsche Traction Management (PTM)',
			'Sistema de áudio BOSE Surround Sound',
			'Painel digital curvado com tela de 12,6"',
			'Modos on-road e off-road com ajuste de altura',
		],
	},
	{
		brand: 'Ferrari',
		model: 'SF90 Stradale',
		matchKeywords: ['sf90'],
		engine: 'V8 biturbo + 3 motores elétricos (PHEV)',
		displacement: '3.990 cc',
		power: '1.000 cv (combinado)',
		torque: '800 Nm',
		acceleration: '2,5 s (0–100 km/h)',
		topSpeed: '340 km/h',
		transmission: 'F1 DCT 8 marchas',
		drivetrain: 'Tração integral (AWD)',
		weight: '1.570 kg',
		fuelConsumption: '7,9 L/100 km (WLTP combinado)',
		length: '4.710 mm',
		width: '1.972 mm',
		height: '1.186 mm',
		wheelbase: '2.650 mm',
		tires: 'Dianteiro: 255/35 ZR20 | Traseiro: 315/30 ZR20',
		brakes: 'Carbono-cerâmicos Brembo, 390 mm (d) / 360 mm (t)',
		fuelTankCapacity: '68 L',
		seatingCapacity: '2 lugares',
		warranty: 'Garantia de fábrica Ferrari',
		highlights: [
			'Primeiro Ferrari com tração integral e sistema híbrido plug-in',
			'Modo eDrive para condução 100% elétrica (até 25 km)',
			'eManettino com 4 modos: eDrive, Hybrid, Performance, Qualify',
			'Aerodinâmica ativa com shut-off Gurney no spoiler traseiro',
			'Display head-up com informações de performance em tempo real',
		],
	},
	{
		brand: 'Ferrari',
		model: 'F8 Tributo',
		matchKeywords: ['f8', 'tributo'],
		engine: 'V8 biturbo',
		displacement: '3.902 cc',
		power: '720 cv a 8.000 rpm',
		torque: '770 Nm a 3.250 rpm',
		acceleration: '2,9 s (0–100 km/h)',
		topSpeed: '340 km/h',
		transmission: 'F1 DCT 7 marchas',
		drivetrain: 'Tração traseira (RWD)',
		weight: '1.330 kg (seco)',
		length: '4.611 mm',
		width: '1.979 mm',
		height: '1.206 mm',
		wheelbase: '2.650 mm',
		brakes: 'Carbono-cerâmicos, 398 mm (d) / 360 mm (t)',
		fuelTankCapacity: '78 L',
		seatingCapacity: '2 lugares',
		warranty: 'Garantia de fábrica Ferrari',
		highlights: [
			'Evolução final do motor V8 Ferrari premiado "International Engine of the Year"',
			'Aerodinâmica derivada da Ferrari 488 Pista',
			'Side Slip Control 6.1 para dinâmica precisa',
			'S-Duct derivado de Fórmula 1 no para-choque dianteiro',
			'Sistema de exaustão com válvulas ativas',
		],
	},
	{
		brand: 'Lamborghini',
		model: 'Huracán',
		matchKeywords: ['huracan', 'huracán'],
		engine: 'V10 aspirado',
		displacement: '5.204 cc',
		power: '640 cv a 8.000 rpm',
		torque: '600 Nm a 6.500 rpm',
		acceleration: '2,9 s (0–100 km/h)',
		topSpeed: '325 km/h',
		transmission: 'LDF 7 marchas (dupla embreagem)',
		drivetrain: 'Tração integral (AWD)',
		weight: '1.382 kg (seco)',
		length: '4.520 mm',
		width: '1.933 mm',
		height: '1.165 mm',
		wheelbase: '2.620 mm',
		tires: 'Dianteiro: 245/30 ZR20 | Traseiro: 305/30 ZR20',
		brakes: 'Carbono-cerâmicos, 380 mm (d) / 356 mm (t)',
		fuelTankCapacity: '83 L',
		seatingCapacity: '2 lugares',
		warranty: 'Garantia de fábrica Lamborghini',
		highlights: [
			'Último V10 aspirado da Lamborghini — motor naturalmente aspirado',
			'Sistema LDVI (Lamborghini Dinamica Veicolo Integrata)',
			'Modos de condução ANIMA: Strada, Sport, Corsa',
			'Chassi híbrido alumínio-carbono',
			'Painel digital TFT de 12,3" com interface HMI',
		],
	},
	{
		brand: 'Lamborghini',
		model: 'Urus',
		matchKeywords: ['urus'],
		engine: 'V8 biturbo',
		displacement: '3.996 cc',
		power: '666 cv a 6.000 rpm',
		torque: '850 Nm entre 2.300–4.500 rpm',
		acceleration: '3,6 s (0–100 km/h)',
		topSpeed: '305 km/h',
		transmission: 'Automática 8 marchas (ZF)',
		drivetrain: 'Tração integral (AWD)',
		weight: '2.197 kg',
		fuelConsumption: '14,2 L/100 km (combinado)',
		trunkCapacity: '616 L',
		length: '5.112 mm',
		width: '2.016 mm',
		height: '1.638 mm',
		wheelbase: '3.003 mm',
		brakes: 'Carbono-cerâmicos opcionais, 440 mm (d) / 370 mm (t)',
		fuelTankCapacity: '85 L',
		seatingCapacity: '5 lugares',
		warranty: 'Garantia de fábrica Lamborghini',
		highlights: [
			'Super SUV mais rápido da categoria',
			'Modos ANIMA: Strada, Sport, Corsa, Neve, Terra, Sabbia',
			'Suspensão pneumática adaptativa com altura variável',
			'Torque vectoring traseiro ativo',
			'Rodas de até 23" — as maiores oferecidas de fábrica',
		],
	},
	{
		brand: 'McLaren',
		model: 'Artura',
		matchKeywords: ['artura'],
		engine: 'V6 biturbo + motor elétrico (PHEV)',
		displacement: '2.993 cc',
		power: '680 cv (combinado)',
		torque: '720 Nm',
		acceleration: '3,0 s (0–100 km/h)',
		topSpeed: '330 km/h',
		transmission: 'SSG 8 marchas (dupla embreagem)',
		drivetrain: 'Tração traseira (RWD)',
		weight: '1.395 kg (seco)',
		length: '4.539 mm',
		width: '1.913 mm',
		height: '1.193 mm',
		wheelbase: '2.640 mm',
		brakes: 'Carbono-cerâmicos, 390 mm (d) / 380 mm (t)',
		fuelTankCapacity: '66 L',
		seatingCapacity: '2 lugares',
		warranty: 'Garantia de fábrica McLaren',
		highlights: [
			'Primeiro McLaren com arquitetura hybrid plug-in de série',
			'Chassi MCLA (McLaren Carbon Lightweight Architecture)',
			'Modo E-Mode para condução elétrica (até 33 km)',
			'Novo motor V6 120 graus desenvolvido do zero',
			'Sistema Proactive Damping Control',
		],
	},
	{
		brand: 'BMW',
		model: 'X5',
		matchKeywords: ['x5'],
		engine: 'Inline 6 cilindros turbo',
		displacement: '2.998 cc',
		power: '340 cv a 5.500–6.500 rpm',
		torque: '450 Nm entre 1.500–5.200 rpm',
		acceleration: '5,4 s (0–100 km/h)',
		topSpeed: '250 km/h (limitado eletronicamente)',
		transmission: 'Steptronic Sport 8 marchas',
		drivetrain: 'Tração integral xDrive (AWD)',
		weight: '2.195 kg',
		fuelConsumption: '9,0 L/100 km (combinado)',
		trunkCapacity: '650 L',
		length: '4.938 mm',
		width: '2.004 mm',
		height: '1.745 mm',
		wheelbase: '2.975 mm',
		fuelTankCapacity: '80 L',
		seatingCapacity: '5 lugares (opcional 7)',
		warranty: 'Garantia de fábrica BMW',
		highlights: [
			'Sistema xDrive com distribuição variável de torque',
			'Suspensão adaptativa com amortecedores eletrônicos',
			'BMW Live Cockpit Professional com telas curvas',
			'Sistema de assistência ao motorista BMW Driving Assistant Professional',
			'Revestimento em couro Vernasca com regulação elétrica',
		],
	},
	{
		brand: 'BMW',
		model: 'X6',
		matchKeywords: ['x6'],
		engine: 'Inline 6 cilindros turbo',
		displacement: '2.998 cc',
		power: '340 cv a 5.500–6.500 rpm',
		torque: '450 Nm entre 1.500–5.200 rpm',
		acceleration: '5,5 s (0–100 km/h)',
		topSpeed: '250 km/h (limitado eletronicamente)',
		transmission: 'Steptronic Sport 8 marchas',
		drivetrain: 'Tração integral xDrive (AWD)',
		weight: '2.260 kg',
		fuelConsumption: '9,5 L/100 km (combinado)',
		trunkCapacity: '580 L',
		length: '4.935 mm',
		width: '2.004 mm',
		height: '1.696 mm',
		wheelbase: '2.975 mm',
		fuelTankCapacity: '83 L',
		seatingCapacity: '5 lugares',
		warranty: 'Garantia de fábrica BMW',
		highlights: [
			'Design coupé com silhueta esportiva sobre plataforma X5',
			'BMW Iconic Glow (grade iluminada)',
			'Teto panorâmico Sky Lounge com iluminação LED',
			'Sistema de som Harman Kardon Surround',
			'Assistente de estacionamento com câmeras 360 graus',
		],
	},
	{
		brand: 'Land Rover',
		model: 'Range Rover Sport',
		matchKeywords: ['range rover', 'sport'],
		engine: 'Inline 6 cilindros turbo mild-hybrid',
		displacement: '2.997 cc',
		power: '400 cv',
		torque: '550 Nm',
		acceleration: '5,7 s (0–100 km/h)',
		topSpeed: '242 km/h',
		transmission: 'Automática ZF 8 marchas',
		drivetrain: 'Tração integral permanente (AWD)',
		weight: '2.360 kg',
		fuelConsumption: '10,8 L/100 km (combinado)',
		trunkCapacity: '835 L',
		length: '4.946 mm',
		width: '2.047 mm',
		height: '1.820 mm',
		wheelbase: '2.997 mm',
		fuelTankCapacity: '80 L',
		seatingCapacity: '5 lugares',
		warranty: 'Garantia de fábrica Land Rover',
		highlights: [
			'Plataforma MLA-Flex com arquitetura elétrica flexível',
			'Suspensão pneumática com Adaptive Dynamics',
			'Terrain Response 2 com modo automático',
			'Sistema Pivi Pro com telas duplas de 13,1"',
			'Capacidade de transposição de água de até 900 mm',
		],
	},
	{
		brand: 'Land Rover',
		model: 'Defender',
		matchKeywords: ['defender'],
		engine: 'Inline 6 cilindros turbo mild-hybrid',
		displacement: '2.997 cc',
		power: '400 cv',
		torque: '550 Nm',
		acceleration: '6,0 s (0–100 km/h)',
		topSpeed: '240 km/h',
		transmission: 'Automática ZF 8 marchas',
		drivetrain: 'Tração integral permanente (AWD)',
		weight: '2.386 kg',
		fuelConsumption: '11,5 L/100 km (combinado)',
		trunkCapacity: '786 L',
		length: '5.018 mm',
		width: '2.008 mm',
		height: '1.967 mm',
		wheelbase: '3.022 mm',
		fuelTankCapacity: '89 L',
		seatingCapacity: '5+2 lugares',
		warranty: 'Garantia de fábrica Land Rover',
		highlights: [
			'Construção monobloco D7x em alumínio — 3x mais rígido que body-on-frame',
			'Terrain Response 2 com modo Wade automático',
			'Ângulo de ataque 38°, saída 40°, rampa 28°',
			'Capacidade de transposição de água de 900 mm',
			'Configurações 90, 110 e 130 (5, 6 ou 8 lugares)',
		],
	},
	{
		brand: 'Chevrolet',
		model: 'Corvette Z06',
		matchKeywords: ['corvette', 'z06'],
		engine: 'V8 LT6 aspirado de rotação plana (flat-plane crank)',
		displacement: '5.525 cc',
		power: '670 cv a 8.400 rpm',
		torque: '623 Nm a 6.300 rpm',
		acceleration: '2,6 s (0–100 km/h)',
		topSpeed: '312 km/h',
		transmission: 'Automática 8 marchas (dupla embreagem)',
		drivetrain: 'Tração traseira (RWD)',
		weight: '1.560 kg',
		length: '4.697 mm',
		width: '2.025 mm',
		height: '1.234 mm',
		wheelbase: '2.722 mm',
		tires: 'Dianteiro: 275/30 ZR20 | Traseiro: 345/25 ZR21',
		brakes: 'Carbono-cerâmicos Brembo, 380 mm (d) / 370 mm (t)',
		fuelTankCapacity: '70 L',
		seatingCapacity: '2 lugares',
		warranty: 'Garantia de fábrica Chevrolet',
		highlights: [
			'Motor V8 aspirado de maior potência específica do mundo (121,5 cv/L)',
			'Virabrequim flat-plane para resposta linear até 8.600 rpm',
			'Motor central traseiro — arquitetura de superesportivo',
			'Chassis com perfil aerodinâmico derivado do Corvette C8.R de corrida',
			'Z07 Performance Package com asa traseira de fibra de carbono',
		],
	},
	{
		brand: 'Chevrolet',
		model: 'Corvette Stingray',
		matchKeywords: ['corvette', 'stingray'],
		engine: 'V8 LT2 aspirado',
		displacement: '6.162 cc',
		power: '495 cv a 6.450 rpm',
		torque: '637 Nm a 5.150 rpm',
		acceleration: '3,0 s (0–100 km/h)',
		topSpeed: '312 km/h',
		transmission: 'Automática 8 marchas (dupla embreagem)',
		drivetrain: 'Tração traseira (RWD)',
		weight: '1.527 kg',
		length: '4.630 mm',
		width: '1.934 mm',
		height: '1.234 mm',
		wheelbase: '2.722 mm',
		brakes: 'Discos ventilados, 345 mm (d) / 350 mm (t)',
		fuelTankCapacity: '70 L',
		seatingCapacity: '2 lugares',
		warranty: 'Garantia de fábrica Chevrolet',
		highlights: [
			'Motor central traseiro — layout de superesportivo',
			'V8 aspirado com som natural incomparável',
			'Modo de condução personalizado com 12 opções de configuração',
			'Teto removível Targa de série',
			'Compartimento de bagagem dianteiro e traseiro',
		],
	},
	{
		brand: 'Dodge',
		model: 'Challenger SRT Hellcat',
		matchKeywords: ['challenger', 'hellcat'],
		engine: 'V8 HEMI supercharged',
		displacement: '6.166 cc',
		power: '717 cv a 6.000 rpm',
		torque: '881 Nm a 4.800 rpm',
		acceleration: '3,6 s (0–100 km/h)',
		topSpeed: '328 km/h',
		transmission: 'Automática TorqueFlite 8HP90 8 marchas',
		drivetrain: 'Tração traseira (RWD)',
		weight: '2.022 kg',
		fuelConsumption: '16,8 L/100 km (combinado)',
		length: '5.017 mm',
		width: '1.923 mm',
		height: '1.448 mm',
		wheelbase: '2.946 mm',
		brakes: 'Brembo 6 pistões (d) / 4 pistões (t), 390 mm (d) / 350 mm (t)',
		fuelTankCapacity: '70 L',
		seatingCapacity: '5 lugares',
		warranty: 'Garantia de fábrica Dodge',
		highlights: [
			'Motor HEMI supercharged — ícone do muscle car americano',
			'Supercharger IHI de 2.380 cc com intercooler',
			'Launch Control e Line Lock de fábrica',
			'SRT Power Chiller para refrigeração do ar de admissão',
			'Widebody com pneus 305/35 ZR20 em todas as rodas',
		],
	},
	{
		brand: 'Mercedes-Benz',
		model: 'AMG GT',
		matchKeywords: ['amg gt', 'amg-gt'],
		engine: 'V8 biturbo handcrafted',
		displacement: '3.982 cc',
		power: '585 cv a 6.100 rpm',
		torque: '800 Nm entre 2.500–5.000 rpm',
		acceleration: '3,2 s (0–100 km/h)',
		topSpeed: '315 km/h',
		transmission: 'AMG SPEEDSHIFT MCT 9 marchas',
		drivetrain: 'Tração integral AMG Performance 4MATIC+',
		weight: '1.795 kg',
		length: '4.725 mm',
		width: '1.985 mm',
		height: '1.354 mm',
		wheelbase: '2.700 mm',
		brakes: 'Compostos AMG de alto desempenho, 390 mm (d) / 360 mm (t)',
		fuelTankCapacity: '80 L',
		seatingCapacity: '2+2 lugares',
		warranty: 'Garantia de fábrica Mercedes-Benz',
		highlights: [
			'Motor V8 handcrafted — "One Man, One Engine"',
			'AMG RIDE CONTROL com suspensão adaptativa',
			'AMG DYNAMIC SELECT com modos de condução',
			'Saída de escapamento dupla AMG Performance com válvulas',
			'AMG Track Pace — telemetria integrada de fábrica',
		],
	},
	{
		brand: 'Bentley',
		model: 'Continental GT',
		matchKeywords: ['continental gt'],
		engine: 'W12 biturbo',
		displacement: '5.950 cc',
		power: '659 cv a 5.000–6.000 rpm',
		torque: '900 Nm entre 1.350–4.500 rpm',
		acceleration: '3,6 s (0–100 km/h)',
		topSpeed: '335 km/h',
		transmission: 'Dupla embreagem 8 marchas',
		drivetrain: 'Tração integral (AWD)',
		weight: '2.244 kg',
		fuelConsumption: '14,0 L/100 km (combinado)',
		trunkCapacity: '358 L',
		length: '4.850 mm',
		width: '1.954 mm',
		height: '1.405 mm',
		wheelbase: '2.851 mm',
		fuelTankCapacity: '90 L',
		seatingCapacity: '2+2 lugares',
		warranty: 'Garantia de fábrica Bentley',
		highlights: [
			'Motor W12 — o grand tourer mais potente da Bentley',
			'Interior em couro artesanal com mais de 10 bilhões de combinações',
			'Rotating Display com tela de 12,3" retrátil',
			'Acabamento em madeira com embutimento diamante',
			'Sistema Bentley Dynamic Ride com barras estabilizadoras ativas de 48V',
		],
	},
	{
		brand: 'Rolls-Royce',
		model: 'Cullinan',
		matchKeywords: ['cullinan'],
		engine: 'V12 biturbo',
		displacement: '6.750 cc',
		power: '571 cv a 5.000 rpm',
		torque: '850 Nm entre 1.600–4.500 rpm',
		acceleration: '5,0 s (0–100 km/h)',
		topSpeed: '250 km/h (limitado eletronicamente)',
		transmission: 'Automática ZF 8 marchas',
		drivetrain: 'Tração integral (AWD)',
		weight: '2.660 kg',
		fuelConsumption: '15,0 L/100 km (combinado)',
		trunkCapacity: '600 L',
		length: '5.341 mm',
		width: '2.000 mm',
		height: '1.835 mm',
		wheelbase: '3.295 mm',
		fuelTankCapacity: '100 L',
		seatingCapacity: '5 lugares',
		warranty: 'Garantia de fábrica Rolls-Royce',
		highlights: [
			'Primeiro SUV da Rolls-Royce — "The Cullinan Diamond"',
			'Plataforma Architecture of Luxury em alumínio spaceframe',
			'Magic Carpet Ride com suspensão pneumática e câmeras preditivas',
			'Portas com mecanismo de fechamento elétrico (coach doors)',
			'Starlight Headliner com 1.344 fibras ópticas no teto',
		],
	},
	{
		brand: 'Ford',
		model: 'Mustang',
		matchKeywords: ['mustang'],
		engine: 'V8 Coyote aspirado',
		displacement: '5.038 cc',
		power: '486 cv a 7.250 rpm',
		torque: '567 Nm a 4.900 rpm',
		acceleration: '4,3 s (0–100 km/h)',
		topSpeed: '250 km/h (limitado eletronicamente)',
		transmission: 'Automática 10 marchas (10R80)',
		drivetrain: 'Tração traseira (RWD)',
		weight: '1.755 kg',
		length: '4.806 mm',
		width: '1.916 mm',
		height: '1.401 mm',
		wheelbase: '2.720 mm',
		brakes: 'Brembo 6 pistões (d), 380 mm (d) / 330 mm (t)',
		fuelTankCapacity: '61 L',
		seatingCapacity: '4 lugares',
		warranty: 'Garantia de fábrica Ford',
		highlights: [
			'Sétima geração do pony car mais icônico do mundo',
			'Motor V8 Coyote com resposta linear até 7.500 rpm',
			'Remote Rev — ligar o motor e ouvir o ronco pelo controle remoto',
			'Drift Brake eletrônico integrado',
			'Painel digital personalizável de 12,4"',
		],
	},
	{
		brand: 'Maserati',
		model: 'MC20',
		matchKeywords: ['mc20'],
		engine: 'V6 Nettuno biturbo',
		displacement: '2.992 cc',
		power: '630 cv a 7.500 rpm',
		torque: '730 Nm entre 3.000–5.500 rpm',
		acceleration: '2,9 s (0–100 km/h)',
		topSpeed: '325 km/h',
		transmission: 'Automática 8 marchas (dupla embreagem)',
		drivetrain: 'Tração traseira (RWD)',
		weight: '1.500 kg (seco)',
		length: '4.669 mm',
		width: '1.965 mm',
		height: '1.224 mm',
		wheelbase: '2.700 mm',
		tires: 'Dianteiro: 245/35 ZR20 | Traseiro: 305/30 ZR20',
		brakes: 'Carbono-cerâmicos Brembo, 380 mm (d) / 350 mm (t)',
		fuelTankCapacity: '60 L',
		seatingCapacity: '2 lugares',
		warranty: 'Garantia de fábrica Maserati',
		highlights: [
			'Motor Nettuno com tecnologia de pré-câmara derivada da F1',
			'Chassi em fibra de carbono com portas borboleta',
			'Aerodinâmica passiva sem asa traseira móvel',
			'Centro de gravidade ultra-baixo (450 mm do solo)',
			'Corsa, GT e Wet — modos de condução dedicados',
		],
	},
]

function normalizeForMatch(s: string): string {
	return s
		.toLowerCase()
		.normalize('NFD')
		.replace(/[\u0300-\u036f]/g, '')
		.trim()
}

/**
 * Find the best matching datasheet for a vehicle based on brand and model.
 * Returns null if no match is found.
 */
export function findVehicleDatasheet(
	brand: string | null | undefined,
	model: string | null | undefined,
	version?: string | null,
): VehicleDatasheet | null {
	if (!brand && !model) return null

	const haystack = normalizeForMatch(
		[brand ?? '', model ?? '', version ?? ''].join(' '),
	)

	let bestMatch: VehicleDatasheet | null = null
	let bestScore = 0

	for (const ds of DATASHEETS) {
		let keywordScore = 0
		let allKeywordsMatch = true
		for (const kw of ds.matchKeywords) {
			if (haystack.includes(normalizeForMatch(kw))) {
				keywordScore += kw.length
			} else {
				allKeywordsMatch = false
			}
		}
		if (!allKeywordsMatch || keywordScore === 0) continue
		let score = keywordScore
		if (normalizeForMatch(ds.brand) && haystack.includes(normalizeForMatch(ds.brand))) {
			score += ds.brand.length * 2
		}
		if (score > bestScore) {
			bestScore = score
			bestMatch = ds
		}
	}

	return bestMatch
}

/**
 * Return all available datasheets (for the Jornada iconic cars section).
 */
export function getAllDatasheets(): VehicleDatasheet[] {
	return DATASHEETS
}
